---
title: "Diplomamunka"
author: "Bokányi Mónika"
date: "2023-03-02"
output: html_document
---
Packagek:
```{r}
library(dplyr)
library(tidyr)
library(lme4)
library(ggplot2)
library(survival)
library(survminer)
library(survAUC)
library(car)
library(lmtest)
library(MASS)
library(glmnet)
```

Adatok beolvasása:
```{r}
library(readxl)
Teljes <- read_excel("C:/Users/bokan/Desktop/Egyetem/BPM/3. félév/Szakszem/Elemzes/Teljes.xlsx")
```

1. Leíró statisztika:

1.1. Teljes adatbázis
```{r}
Teljes[Teljes=="NA"]<-NA

table(Teljes$PrevUnemp)
1098/14652 #7,5% volt munkanélküli
ggplot(Teljes, aes(x=PrevUnemp, fill=PrevUnemp))+geom_bar()+ggtitle("A koronavírus által munkanélkülivé váltak száma")+theme(plot.title = element_text(hjust = 0.5))+labs(x="Volt-e munkanélküli", y="fő")+scale_x_discrete(labels = c("Igen", "Nem"), name = "Került-e munkanélküliségbe?")+labs(fill="Volt-e munkanélküli?")+scale_fill_discrete(labels=c('Igen', 'Nem'))+guides(fill=FALSE)+theme(panel.border = element_rect(color = "black", fill = NA, size = 0.3))
```

Életkor:
```{r}
Teljes$BirthYear <- as.numeric(Teljes$BirthYear)
max(Teljes$BirthYear)
min(Teljes$BirthYear)
summary(Teljes$BirthYear) #min 1916, max: 1991, mean:1956, medián:1958
barplot(table(Teljes$BirthYear)) #1959 és 1960-ban születtek a legtöbben
ggplot(Teljes, aes(x=BirthYear, fill=I("coral1")))+geom_bar()+ggtitle("A teljes adatbázis születési éve")+theme(plot.title = element_text(hjust = 0.5))+labs(x="Születési év", y="fő")+theme(panel.border = element_rect(color = "black", fill = NA, size = 0.3))
```

Cenzorálás:
```{r}
Teljes$Unemp01 <- ifelse(Teljes$Status=="2. Employed or self-employed (including working for family business)", 1, 0)
table(Teljes$Unemp01)
6341/(6341+8311) #itt 43% cenzorált
table(Teljes$Status)
```

Egyéb:
```{r}
table(Teljes$`Covid _vaccine`)
3177/(3177+11475) #21% nem oltatott

table(Teljes$FinancialSituation)
table(Teljes$RepFinancialSituation)

table(Teljes$GovHelp)
table(Teljes$Country) #118 magyar
UnempData <- Teljes %>% filter(Teljes$PrevUnemp=="1. Yes")
table(UnempData$Country)
```


1.2. Szűrt adatbázis (munkanélküliek)
```{r}
#Akik voltak korábban munkanélküliek (akikkel foglalkozunk):
table(Teljes$PrevUnemp)
UnempData <- Teljes %>% filter(Teljes$PrevUnemp=="1. Yes")

#a Hány hetet voltak munka nélkül változóban (Cox eredményváltozója) az NA-k kezelése:
summary(UnempData$UnempTimeInWeeks)
UnempData$UnempTimeInWeeks <- as.factor(UnempData$UnempTimeInWeeks)
table(UnempData$UnempTimeInWeeks)
UnempData$UnempTimeInWeeks <- as.numeric(UnempData$UnempTimeInWeeks)
38/1098 #3,5%

#Inputáljuk:
mean(UnempData$UnempTimeInWeeks, na.rm=T) #26 héttel inputálunk
UnempData$UnempTimeInWeeks <- replace_na(UnempData$UnempTimeInWeeks, 26)
UnempData$Unemp01 <- ifelse(UnempData$Status=="2. Employed or self-employed (including working for family business)", 1, 0)
?Surv #1 dead, 0 alive
```

Eredményvált:
```{r}
summary(UnempData$UnempTimeInWeeks)#min: 1 hét, max: 60 hét, medián:23
mean(UnempData$UnempTimeInWeeks) #Átlagos idő munkanélküliségben: 26 hét
barplot(table(UnempData$UnempTimeInWeeks))
hist(UnempData$UnempTimeInWeeks)
shapiro.test(UnempData$UnempTimeInWeeks) #nem norm.
ggplot(UnempData, aes(x=1, y=UnempTimeInWeeks, fill=I("cyan3")))+geom_boxplot()+geom_violin(alpha=0.3)+coord_flip()+ggtitle("Munkanélküliségben töltött hetek dobozábrája")+labs(y="Munkanélküliségben töltött hetek száma")+theme(plot.title = element_text(hjust = 0.5))+theme(panel.border = element_rect(color = "black", fill = NA, size = 0.3))

UnempData$BirthYear <- as.numeric(UnempData$BirthYear)
summary(UnempData$BirthYear)
hist(UnempData$BirthYear)
barplot(table(UnempData$BirthYear)) #1959 és 1960-ban születtek a legtöbben
shapiro.test(UnempData$BirthYear) #nem norm.

# cor.test(x=UnempData$UnempTimeInWeeks, y=UnempData$BirthYear) #nincs kapcs.
# 
# #H^2 statisztika számítása (nem és idő):
# nem <- lm(UnempTimeInWeeks ~ Gender, data=UnempData)
# summary(nem)
#       # SST és SSB számítása
# SST <- sum((UnempData$UnempTimeInWeeks - mean(UnempData$UnempTimeInWeeks))^2)
# SSB <- sum((predict(nem) - mean(UnempData$UnempTimeInWeeks))^2)
# 
#       # H^2 számítása
# H2 <- SSB / SST
# H2
# sqrt(H2) #nincs kapcs
# #H^2 statisztika számítása (ország és idő):
# orszag <- lm(UnempTimeInWeeks ~ Country, data=UnempData)
# summary(orszag)
#       # SST és SSB számítása
# SST <- sum((UnempData$UnempTimeInWeeks - mean(UnempData$UnempTimeInWeeks))^2)
# SSB <- sum((predict(orszag) - mean(UnempData$UnempTimeInWeeks))^2)
# 
#       # H^2 számítása
# H2 <- SSB / SST
# H2
# sqrt(H2)
# #gyenge kapcs
# 
# #H^2 statisztika számítása (oltott-e és idő):
# oltas <- lm(UnempTimeInWeeks ~ `Covid _vaccine`, data=UnempData)
# summary(oltas)
#       # SST és SSB számítása
# SST <- sum((UnempData$UnempTimeInWeeks - mean(UnempData$UnempTimeInWeeks))^2)
# SSB <- sum((predict(oltas) - mean(UnempData$UnempTimeInWeeks))^2)
# 
#       # H^2 számítása
# H2 <- SSB / SST
# H2
# sqrt(H2)
# #nincs kapcs
# 
# #H^2 statisztika számítása (Health és idő):
# health <- lm(UnempTimeInWeeks ~ Health, data=UnempData)
# summary(health)
#       # SST és SSB számítása
# SST <- sum((UnempData$UnempTimeInWeeks - mean(UnempData$UnempTimeInWeeks))^2)
# SSB <- sum((predict(health) - mean(UnempData$UnempTimeInWeeks))^2)
#       # H^2 számítása
# H2 <- SSB / SST
# H2
# sqrt(H2)
# #nincs kapcs
# 
# with(UnempData, t.test(UnempTimeInWeeks ~ Gender))
```

Cenzorálás:
```{r}
table(UnempData$Unemp01) 
297/(297+801) #27%, ami cenzorált (aki nem talált munkahelyet a felmérésig)
```

Egyéb:
```{r}
table(UnempData$`Covid _vaccine`)
255/(255+843) #23% nem oltatott

table(UnempData$FinancialSituation)
table(UnempData$RepFinancialSituation)

table(UnempData$GovHelp)
table(UnempData$Country)
head(UnempData %>% filter(Country=="Hungary"))

UnempData$SurvObj <- UnempData$UnempTimeInWeeks
```

2. Logit modell
```{r}
#Nevek változtatása (technikai)
names(Teljes)[names(Teljes) == "Covid _vaccine"] <- "CovidVaccine"
names(Teljes)[names(Teljes) == "Rokoni támogatás"] <- "Rokoni_támogatás"
names(Teljes)[names(Teljes) == "Munkáltatói támogatás"] <- "Munkáltatói_támogatás"

#Eredményvált. alakítása 0-1-é:
Teljes$PrevUnemp <- ifelse(Teljes$PrevUnemp=="1. Yes", 1, 0)
Teljes$PrevUnemp <- as.numeric(Teljes$PrevUnemp)

#tanító és tesztelő adatbázis:
set.seed(1)
sample <- sample(c(TRUE, FALSE), nrow(Teljes), replace=TRUE, prob=c(0.8,0.2))
train  <- Teljes[sample, ]
test   <- Teljes[!sample, ]

logit0 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+HelpFromRelatives+Rokoni_támogatás+Munkáltatói_támogatás+Neckfarc+Diabetes+Hypertension+Heartattack+Lung_disease+Other_problem+Medicine+CovidVaccine+RepFinancialSituation+VoluntaryWork+InternetConnection+GoodThings,family = binomial("logit"),data = train)
summary(logit0)

logit1 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+Gender+BirthYear+Health+Neckfarc+Diabetes+Hypertension+Heartattack+Lung_disease+Other_problem+Medicine+CovidVaccine+RepFinancialSituation+VoluntaryWork+InternetConnection+GoodThings,family = binomial("logit"),data = train)
summary(logit1) # Status, AddFinSupp, BirthYear, Health
logit1 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+HelpFromRelatives+Rokoni_támogatás+Munkáltatói_támogatás,family = binomial("logit"),data = train)
summary(logit1) #RepWorkEnvironment, RepLowestWorkingHours, RepHighestWorkingHours, RepCountHLMonthlyIncome, Munkáltatói támogatás

#A kiválasztott változókat belerakom, majd backward elimináció:
logit2 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+Gender+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+Munkáltatói_támogatás,family = binomial("logit"),data = train)
summary(logit2) #AIC:5000,6

#Gendert kiveszem
logit3 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+Munkáltatói_támogatás,family = binomial("logit"),data = train)
summary(logit3) #4999,4
BIC(logit3) #5131,953

#Ha kiveszem a Health-et:
logit4 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+Munkáltatói_támogatás,family = binomial("logit"),data = train)
summary(logit4) #AIC: 5010,6 (nőtt, így a Health bent marad!)

#Ha kiveszem a munkáltatói támogatást
logit5 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome,family = binomial("logit"),data = train)
summary(logit5) #AIC:5003,3 (nőtt, szóval ez is benne marad!) #eddig a logit3 a jó!

#Országgal (nyelv csak rontotta)
logit7 <- glm(as.factor(PrevUnemp) ~Status+AddFinSupp+BirthYear+Health+RepWorkEnvironment+RepLowestWorkingHours+RepHighestWorkingHours+TreatedInHospital+RepCountHLMonthyIncome+Munkáltatói_támogatás+Country,family = binomial("logit"),data = train)
summary(logit7) #AIC:4924
BIC(logit7) #5255
#AIC javul, BIC romlik, én BIC alapján döntök, az országot nem veszem be, logit3 modell marad.

#Végleges: (Kivettem a munkával kapcsolatos változókat)
logit8 <- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital+RepCountHLMonthyIncome,family = binomial("logit"),data = train)
summary(logit8) #AIC: 5783,7
BIC(logit8) #BIC: 5842,65

#Kilógó értékek:
train[abs(rstudent(logit8))>3,] -> kilogok #nincs kilógó
train  <- train[abs(rstudent(logit8))<=3, ]
#repcountincome nélkül, mert nem etikus, hogy ezt a biztosító megkérdezze, rossz hírnév kockáztatása
logit9 <- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital,family = binomial("logit"),data = train)
summary(logit9) #AIC: 5963.8
BIC(logit9) #BIC: 6015.395 #rosszabb a 8-asnál

vif(logit8)
resettest(logit8) #A modell nem jól specifikált
crPlots(logit8, ~Health)
crPlots(logit8, ~BirthYear)
crPlots(logit8, ~TreatedInHospital)
crPlots(logit8, ~RepCountHLMonthyIncome)

#Interakció Birth-Health szignifikáns lesz
logit10 <- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital+RepCountHLMonthyIncome+BirthYear:Health,family = binomial("logit"),data = train)
summary(logit10) #AIC: 5771
BIC(logit10) #5860

#Interakció Birth-TreatedInHospital -> nem szinifik.
logit11 <- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital+RepCountHLMonthyIncome+BirthYear:Health+BirthYear:TreatedInHospital,family = binomial("logit"),data = train)
summary(logit11) #AIC: 5773
BIC(logit11) #5869
#Interakció: RepCountHLMOntlyInceom, -> nem szignifikáns
logit12 <- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital+RepCountHLMonthyIncome+BirthYear:Health+BirthYear:RepCountHLMonthyIncome,family = binomial("logit"),data = train)
summary(logit12) #AIC: 5773
BIC(logit12) #5869

#LOGIT10 a végső modell
#Még megnézzük a repCountHLMonthlyIncome nélkül is, mert nem etik. h a bizt. megkérdezze:
logit<- glm(as.factor(PrevUnemp) ~BirthYear+Health+TreatedInHospital+BirthYear:Health,family = binomial("logit"),data = train)
summary(logit) #AIC: 5947
BIC(logit) #6028

resettest(logit10)
mean(Teljes$PrevUnemp)
#Becslés:
becsles <- predict(logit10, test, type="response")
test$becsult <- ifelse(becsles>0.08, 1,0)
xtabs(~PrevUnemp+becsult, test)
sum(test$PrevUnemp==test$becsult)/nrow(test)

becsles <- predict(logit, test, type="response")
test$becsult <- ifelse(becsles>0.08, 1,0)
xtabs(~PrevUnemp+becsult, test)
sum(test$PrevUnemp==test$becsult)/nrow(test)

#ROC:
library("pROC")
ROCgorbe <- roc(test$PrevUnemp~becsles)
ggroc(ROCgorbe)+ggtitle("A jövedelem nélküli logisztikus regresszió ROC-görbéje")+theme(plot.title = element_text(hjust = 0.5))+labs(y="Szenzitivitás")+labs(x="Specificitás")
auc(ROCgorbe)
2*auc(ROCgorbe)-1

#RepCountHL nélkül: találati arány 0,66, AUC 0,626 és gini 0,252
#A rendes végleges modell: találati ar 0,755, AUC  0,669 és gini 0,338
```


3. Túlélés elemzés
```{r}
#Kaplan-Meier:
#Alaptúlélés:
UnempData$SurvObj <- with(UnempData, Surv(UnempTimeInWeeks, Unemp01)) 
AlapTuleles <- survfit(SurvObj ~ 1, data = UnempData)
summary(AlapTuleles)
ggsurvplot(AlapTuleles, xlab = "Munkanélkülivé válás óta eltelt hetek száma", ylab = "Továbbra is munkanélküliek aránya")

#Nem:
TulelesNem <- survfit(SurvObj ~ Gender, data = UnempData)
summary(TulelesNem)
ggsurvplot(TulelesNem,
           xlab = "Munkanélkülivé válás óta eltelt hetek száma",
           ylab = "Továbbra is munkanélküliek aránya",
           censor = FALSE,
           pval = TRUE,
           legend.labs=c("Férfi", "Nő"))
survdiff(SurvObj ~ Gender, data = UnempData) #A nem, nem szignifikáns a Mantel-Cox teszt alapján, p=0,9

#Vakcina:
names(UnempData)[names(UnempData) == "Covid _vaccine"] <- "CovidVaccine"
TulelesVakcina <- survfit(SurvObj ~ CovidVaccine, data = UnempData)
summary(TulelesVakcina)
ggsurvplot(TulelesVakcina,
           xlab = "Munkanélkülivé válás óta eltelt hetek száma",
           ylab = "Továbbra is munkanélküliek aránya",
           censor = TRUE,
           pval = TRUE,
           legend.labs=c("Kapott vakcinát", "Nem kapott vakcinát"))
survdiff(SurvObj ~ CovidVaccine, data = UnempData) #p=0,4 nem szignifikáns

#Kormánytámogatás:
TulelesKormanyTamog <- survfit(SurvObj ~ GovHelp, data = UnempData)
summary(TulelesKormanyTamog)
ggsurvplot(TulelesKormanyTamog,
           xlab = "Munkanélkülivé válás óta eltelt hetek száma",
           ylab = "Továbbra is munkanélküliek aránya",
           censor = FALSE,
           conf.int = TRUE,
           pval.method = TRUE,
           pval = TRUE,
           legend.labs=c("Nincs extra segély", "Van extra segély"))
survdiff(SurvObj ~ GovHelp, data = UnempData) # p kb 0,47 A kormánytámogatás sem szignifikáns.

UnempData$RepAidFriendsRelatives <- UnempData$RepAid
colnames(UnempData)[42] ="Rokonitamogatas"

#Cox-regresszió:
set.seed(110)
sample <- sample(c(TRUE, FALSE), nrow(UnempData), replace=TRUE, prob=c(0.8,0.2))
train2  <- UnempData[sample, ]
test2   <- UnempData[!sample, ]

#Modell:
CR <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~BirthYear+Health+FinancialSituation+Lung_disease+RepAidFriendsRelatives+Neckfarc+Heartattack+Diabetes+Tumor+Lung_disease+VoluntaryWork+GoodThings+Other_problem+CovidVaccine+Medicine+InternetConnection+HelpFromChindren+HelpFromRelatives+HelpFromFriends+HelpFromFriends+Gender+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours, data=train2)
summary(CR)

#Kilógó:
plot(resid(CR,type='deviance')) #nem volt
train2$reziduum <- resid(CR,type='deviance')
train2 <- train2[train2$reziduum > -3 & train2$reziduum < 3,]
train2$reziduum <- NULL
#Újra
CR <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+FinancialSituation+Lung_disease+RepAidFriendsRelatives+Neckfarc+Heartattack+Diabetes+Tumor+Lung_disease+VoluntaryWork+GoodThings+Other_problem+CovidVaccine+Medicine+InternetConnection+HelpFromChindren+Gender+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours, data=train2)
summary(CR)
#stepwise
stepwise.mod<-stepAIC(CR, direction="both")
stepwise.mod


#Megoldás:
CR <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+VoluntaryWork+HelpFromChindren+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours, data=train2)
summary(CR)

#Átlagos túlélés:
 H0t <- basehaz(CR)
 atlagos_tuleles <- exp(-H0t$hazard)
 plot(atlagos_tuleles)

 #Arányossági felt.:
 PH_check<-cox.zph(fit=CR,transform = "km", global = TRUE)
plot(PH_check)
PH_check #Health és RepHighestWorkingHours 5%on szignifikáns, azaz nem teljesül a feltevés.

#Anova:
aovHealth <- aov(UnempTimeInWeeks~Health, data=train2)
summary(aovHealth)
1852   /304399   

aovLung <- aov(UnempTimeInWeeks~Lung_disease, data=train2)
summary(aovLung)
(629   /305623   )

aovFin <- aov(UnempTimeInWeeks~FinancialSituation, data=train2)
summary(aovFin)
933   /305318   

aovRepAid <- aov(UnempTimeInWeeks~RepAidFriendsRelatives, data=train2)
summary(aovRepAid)
359   /305892   

aovChildren <- aov(UnempTimeInWeeks~HelpFromChindren, data=train2)
summary(aovChildren)
743   /305509   

#Interakció:
train2$Hworkhours <- 0
train2$Hworkhours[train2$RepHighestWorkingHours=="Replied"] <- 1
train2$Time_HWorkH <- train2$UnempTimeInWeeks * train2$Hworkhours

train2$Health1 <- 0
train2$Health1[train2$Health=="5. Poor"] <- 1
train2$Time_HealthPoor <- train2$UnempTimeInWeeks * train2$Health1

train2$Health2 <- 0
train2$Health2[train2$Health=="2. Very good"] <- 1
train2$Time_HealthVgood <- train2$UnempTimeInWeeks * train2$Health2

train2$Health3 <- 0
train2$Health3[train2$Health=="3. Good"] <- 1
train2$Time_HealthGood <- train2$UnempTimeInWeeks * train2$Health3

train2$Health4 <- 0
train2$Health4[train2$Health=="4. Fair"] <- 1
train2$Time_HealthFair <- train2$UnempTimeInWeeks * train2$Health4

test2$Health1 <- 0
test2$Health1[test2$Health=="5. Poor"] <- 1
test2$Time_HealthPoor <- test2$UnempTimeInWeeks * test2$Health1

test2$Health2 <- 0
test2$Health2[test2$Health=="2. Very good"] <- 1
test2$Time_HealthVgood <- test2$UnempTimeInWeeks * test2$Health2

test2$Health3 <- 0
test2$Health3[test2$Health=="3. Good"] <- 1
test2$Time_HealthGood <- test2$UnempTimeInWeeks * test2$Health3

test2$Health4 <- 0
test2$Health4[test2$Health=="4. Fair"] <- 1
test2$Time_HealthFair <- test2$UnempTimeInWeeks * test2$Health4
#Korrigált modell:
CR <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+VoluntaryWork+HelpFromChindren+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours+Time_HWorkH+Time_HealthVgood+Time_HealthGood+Time_HealthFair+Time_HealthPoor, data=train2) #time-Highest working hours nem szignifk., nem szükséges az időfüggő együttható
summary(CR)
 #voluntary kiveszem
CR <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours+Time_HealthVgood+Time_HealthGood+Time_HealthFair+Time_HealthPoor, data=train2)
summary(CR)

CR1 <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+RepCountHLMonthyIncome+RepLowestWorkingHours+RepHighestWorkingHours+Time_HealthVgood+Time_HealthGood+Time_HealthFair+Time_HealthPoor, data=train2)
summary(CR1)

#income nélkül
CR2 <- coxph(Surv(UnempTimeInWeeks,Unemp01==1)~Health+RepLowestWorkingHours+RepHighestWorkingHours+Time_HealthVgood+Time_HealthGood+Time_HealthFair+Time_HealthPoor, data=train2)
summary(CR2)

#Teljesítmény (CR1):
lp <- predict(CR1, newdata=train2) #predikció a tanuló mintára
lpnew <- predict(CR1, newdata=test2) #predikció a teszt mintára
Surv.rsp <- train2$SurvObj #valós eredményváltozó értékek a tanuló mintán
Surv.rsp.new <- test2$SurvObj #valós eredményváltozó értékek a teszt mintán

BeggC(Surv.rsp, Surv.rsp.new, lp, lpnew) #0,898
ggforest(CR1)
?ggforest
#Teljesítmény (CR2):
lp <- predict(CR2, newdata=train2) #predikció a tanuló mintára
lpnew <- predict(CR2, newdata=test2) #predikció a teszt mintára
Surv.rsp <- train2$SurvObj #valós eredményváltozó értékek a tanuló mintán
Surv.rsp.new <- test2$SurvObj #valós eredményváltozó értékek a teszt mintán

BeggC(Surv.rsp, Surv.rsp.new, lp, lpnew) #0,9011
ggforest(CR2)
```

4. LASSO-Cox
```{r}
y <- with(UnempData, Surv(UnempData$UnempTimeInWeeks, Unemp01))
vars<-c("BirthYear","RepCountHLMonthyIncome")
VoluntaryDummy<- model.matrix(~VoluntaryWork-1, data=UnempData)
VoluntaryDummyYes <- VoluntaryDummy[,-2]
LowHoursDummy <- model.matrix(~RepLowestWorkingHours-1, data=UnempData)
LowHoursDummyReplied <- LowHoursDummy[,-1]
HighHoursDummy <- model.matrix(~RepHighestWorkingHours-1, data=UnempData)
HighHoursDummyReplied <- HighHoursDummy[, -1]
Health <- model.matrix(~Health-1, data=UnempData)
HealthDummy <- Health[,-1]
# #-----
# #interakciók:
# UnempData$Health1 <- 0
# UnempData$Health1[UnempData$Health=="5. Poor"] <- 1
# UnempData$Time_HealthPoor <- UnempData$UnempTimeInWeeks * UnempData$Health1
# 
# UnempData$Health2 <- 0
# UnempData$Health2[UnempData$Health=="2. Very good"] <- 1
# UnempData$Time_HealthVgood <- UnempData$UnempTimeInWeeks * UnempData$Health2
# 
# UnempData$Health3 <- 0
# UnempData$Health3[UnempData$Health=="3. Good"] <- 1
# UnempData$Time_HealthGood <- UnempData$UnempTimeInWeeks * UnempData$Health3
# 
# UnempData$Health4 <- 0
# UnempData$Health4[UnempData$Health=="4. Fair"] <- 1
# UnempData$Time_HealthFair <- UnempData$UnempTimeInWeeks * UnempData$Health4
# 
# Time_HealthPoor <- model.matrix(~Time_HealthPoor-1, data=UnempData)
# Time_HealthVgood <- model.matrix(~Time_HealthVgood-1, data=UnempData)
# Time_HealthGood <- model.matrix(~Time_HealthGood-1, data=UnempData)
# Time_HealthFair <- model.matrix(~Time_HealthFair-1, data=UnempData)
#---
Vaccine <- model.matrix(~CovidVaccine-1, data=UnempData)
VaccineDummyYes <- Vaccine[, -2]
Hospital <- model.matrix(~TreatedInHospital-1, data=UnempData)
HospitalDummyYes <- Hospital[, -2]
Children <- model.matrix(~HelpFromChindren-1, data=UnempData)
ChildrenDummyYes <- Children[, -2]
Financial <- model.matrix(~FinancialSituation-1, data=UnempData)
FinancialDummy <- Financial[, -4]
Lung <- model.matrix(~Lung_disease-1, data=UnempData)
LungdisYes <- Lung[, -2]
RepAidFriendsRelativesYes <- model.matrix(~RepAidFriendsRelatives-1, data=UnempData)
NeckFarc <- model.matrix(~Neckfarc-1, data=UnempData)
NeckfarcYes <- NeckFarc[, -2]
Heartattack <- model.matrix(~Heartattack-1, data=UnempData)
HeartattackYes <- Heartattack[, -2]
Diabetes <- model.matrix(~Diabetes-1, data=UnempData)
DiabetesYes <- Diabetes[, -2]
Tumor <- model.matrix(~Tumor-1, data=UnempData)
TumorYes <- Tumor[, -2]
GoodThings <- model.matrix(~GoodThings-1, data=UnempData)
GoodThingsDummy <- GoodThings[, -2]
OtherProblem <- model.matrix(~Other_problem-1, data=UnempData)
OtherProblemYes <- OtherProblem[, -2]
Medicine <- model.matrix(~Medicine-1, data=UnempData)
MedicineYes <- Medicine[, -2]
InternetConnection <- model.matrix(~InternetConnection-1, data=UnempData)
InternetConnectionYes <- InternetConnection[, -2]
Relatives <- model.matrix(~HelpFromRelatives-1, data=UnempData)
RelativesDummyYes <- Relatives[, -2]
Friends <- model.matrix(~HelpFromFriends-1, data=UnempData)
FriendsnDummyYes <- Friends[, -2]
Gender <- model.matrix(~Gender-1, data=UnempData)
GenderMale <- Gender[, -2]

# x <- cbind(UnempData[,vars], VoluntaryDummyYes,LowHoursDummyReplied, HighHoursDummyReplied,HealthDummy,VaccineDummyYes, HospitalDummyYes, ChildrenDummyYes, FinancialDummy, LungdisYes,RepAidFriendsRelativesYes, NeckfarcYes, HeartattackYes, DiabetesYes,TumorYes,  OtherProblemYes, MedicineYes, InternetConnectionYes, RelativesDummyYes, FriendsnDummyYes, GenderMale, Time_HealthFair, Time_HealthGood, Time_HealthVgood, Time_HealthPoor)

#Az interakciók bevonásánál nem vett ki egyetlen változót sem. Erős modell lett a végeredmény, de a rengeteg változóval túlillesztés történt.

 x <- cbind(UnempData[,vars], VoluntaryDummyYes,LowHoursDummyReplied, HighHoursDummyReplied,HealthDummy,VaccineDummyYes, HospitalDummyYes, ChildrenDummyYes, FinancialDummy, LungdisYes,RepAidFriendsRelativesYes, NeckfarcYes, HeartattackYes, DiabetesYes,TumorYes,  OtherProblemYes, MedicineYes, InternetConnectionYes, RelativesDummyYes, FriendsnDummyYes, GenderMale)
 x <- as.matrix(x)
 
lambdak<-cv.glmnet(x, y, alpha=1, family="cox")$lambda
lassocox<-cv.glmnet(x, y, family="cox", alpha=1)
lassocox$lambda.min -> L
plot(lassocox)
summary(lassocox)
coef(lassocox)

lassocox2 <- glmnet(x, y, family = "cox", lambda=L, alpha=1)
coef(lassocox2)
pred <- predict(lassocox2, newx = x, lambda=L)

cindex <- Cindex(pred, y)
cindex #0,6039

#Income nélkül

vars<-c("BirthYear")
 x <- cbind(UnempData[,vars], VoluntaryDummyYes,LowHoursDummyReplied, HighHoursDummyReplied,HealthDummy,VaccineDummyYes, HospitalDummyYes, ChildrenDummyYes, FinancialDummy, LungdisYes,RepAidFriendsRelativesYes, NeckfarcYes, HeartattackYes, DiabetesYes,TumorYes,  OtherProblemYes, MedicineYes, InternetConnectionYes, RelativesDummyYes, FriendsnDummyYes, GenderMale)
 x <- as.matrix(x)

lambdak<-cv.glmnet(x, y, alpha=1, family="cox")$lambda
lassocox<-cv.glmnet(x, y, family="cox", alpha=1, nfolds = 10)
lassocox$lambda.min -> L
plot(lassocox)
summary(lassocox)
coef(lassocox)

lassocox3 <- glmnet(x, y, family = "cox", lambda=L, alpha=1)
coef(lassocox3)
pred3 <- predict(lassocox3, newx = x, lambda=L)

cindex <- Cindex(pred3, y)
cindex #0,6027
```

Várható érték elv:

```{r}
UnempData$Hworkhours <- 0
UnempData$Hworkhours[UnempData$RepHighestWorkingHours=="Replied"] <- 1
UnempData$Time_HWorkH <- UnempData$UnempTimeInWeeks * UnempData$Hworkhours

UnempData$Health1 <- 0
UnempData$Health1[UnempData$Health=="5. Poor"] <- 1
UnempData$Time_HealthPoor <- UnempData$UnempTimeInWeeks * UnempData$Health1

UnempData$Health2 <- 0
UnempData$Health2[UnempData$Health=="2. Very good"] <- 1
UnempData$Time_HealthVgood <- UnempData$UnempTimeInWeeks * UnempData$Health2

UnempData$Health3 <- 0
UnempData$Health3[UnempData$Health=="3. Good"] <- 1
UnempData$Time_HealthGood <- UnempData$UnempTimeInWeeks * UnempData$Health3

UnempData$Health4 <- 0
UnempData$Health4[UnempData$Health=="4. Fair"] <- 1
UnempData$Time_HealthFair <- UnempData$UnempTimeInWeeks * UnempData$Health4

#Kárnagyság Cox:
coxweeks <- predict(CR1, newdata=UnempData)
coxweeks

#Bekövetkezési valószínűségek:
becslesfinal <- predict(logit10, UnempData, type="response")

#Várható érték:
becslesfinal*coxweeks -> EX
EX
sum(EX)

hist(EX, main="Várható munkanélkülsiégben töltött hetek száma", ylab = "Gyakoriság", col="salmon")
hist(becslesfinal)
hist(coxweeks)
mean(coxweeks)
mean(becslesfinal)
plot(becslesfinal)
mean(EX)
plot(EX)

#40 órával heti bérre számolva, 2 csoportra:
heti_kisebb <- 3000*40*0.7
heti_nagyobb <- 7000*40*0.7
EX_hetikisebb <- heti_kisebb*EX #várhatóan hány hetet munkanélküli*heti jövedelem
mean(EX_hetikisebb) #első csoport átlagos kifizetés
EX_hetinagyobb <- heti_nagyobb*EX
mean(EX_hetinagyobb) #második csoport átlagos kifizetés

kisdij <- sum(EX_hetikisebb)/1098
nagydij <- sum(EX_hetinagyobb)/1098

havidijK <- kisdij/36
havidijN <- nagydij/36
havidijK*1.2
havidijN*1.2
kisdij
nagydij
```




